@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MzQwNDg4ODh9.RLJVp3U43R0g_nQuDxh3gDVFlGX8qb2Q0-bLw3nRjGU


### Users create (signup)
  POST http://localhost:3000/users
  Content-Type: application/json

  {
    "name": "user4",
    "email": "user4@test.com",
    "password": "password",
    "password_confirmation": "password"
  }


### Sessions create (login)
  POST http://localhost:3000/sessions
  Content-Type: application/json

  {
    "email": "test@test.com",
    "password": "password"
  }






### PRODUCTS INDEX
GET http://localhost:3000/products.json
Content-Type: application/json

### PRODUCTS DESTROY
DELETE http://localhost:3000/products/5.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

### PRODUCTS CREATE
POST http://localhost:3000/products.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "name": "Test",
  "price": 100,
  "description": "Test",
  "supplier_id": 1
}





### ORDERS INDEX
GET http://localhost:3000/orders.json
Authorization: Bearer {{jwt}}

### ORDERS CREATE
POST http://localhost:3000/orders.json
Authorization: Bearer {{jwt}}
Content-Type: application/json



### ORDERS SHOW
GET http://localhost:3000/orders/1.json
Authorization: Bearer {{jwt}}



### CREATE CART

post http://localhost:3000/carted_products
Content-Type: application/json
Authorization: Bearer {{jwt}}


{
  "product_id": 2, 
  "quantity": 5
}


### SHOW INDEX FOR CARTED PRODUCTS
get http://localhost:3000/carted_products
Content-Type: application/json
Authorization: Bearer {{jwt}}


### DELETE ITEM FROM CARTED PRODUCTS
delete http://localhost:3000/carted_products/1.as_json
Content-Type: application/json
Authorization: Bearer {{jwt}}

