@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MzE2Mjk3MTZ9.7Fjcw1oKe2PJp615WcaK0MQsKSd3OgSckwzJnaeClng

### Users create (signup)
  POST http://localhost:3000/users
  Content-Type: application/json
  {
    "name": "Test",
    "email": "test@test.com",
    "password": "password",
    "password_confirmation": "password"
  }
### Sessions create (login)
  POST http://localhost:3000/sessions
  Content-Type: application/json

  {
    "email": "test@test.com",
    "password": "password"
  }






### PRODUCTS INDEX
GET http://localhost:3000/products.json
Content-Type: application/json

### PRODUCTS DESTROY
DELETE http://localhost:3000/products/8.json





### ORDERS INDEX
GET http://localhost:3000/orders.json
Authorization: Bearer {{jwt}}

### ORDERS CREATE
POST http://localhost:3000/orders.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "product_id": 2,
  "quantity": 4
}

### ORDERS SHOW
GET http://localhost:3000/orders/1.json
Authorization: Bearer {{jwt}}